"use client"
import { useState } from 'react';
import Title from '../../ui/components/title';
import Image from 'next/image';
import TechImg1 from './../../../img/sustainability/image.XUX8M2.png'
import TechImg5 from './../../../img/sustainability/Sostenibilita.png'
import EndPage from '../../ui/components/end-page';
import Description from '../../ui/components/description';
import Link from 'next/link';
import Button from '../../ui/components/button';
import Footer from '@/app/ui/dashboard-en/footer';
import Navbar from '@/app/ui/dashboard-en/navbar';

export default function Page() {
    const [showRobot, setShowRobot] = useState(true);
    const [showLine, setShowLine] = useState(false);
    const [showIsland, setShowIsland] = useState(false);

    const openTab = (title: any) => {
        switch (title) {
            case 'Robot':
                setShowLine(false);
                setShowIsland(false);
                setShowRobot(true);
                break;
            case 'Lines':
                setShowRobot(false);
                setShowIsland(false);
                setShowLine(true);
                break;
            case 'Islands':
                setShowRobot(false);
                setShowLine(false);
                setShowIsland(true);
                break;
            default:
                break;
        }
    }

    return (
        <>
            <Navbar/>
            <Title title={'Sustainability'} />
            <Description 
                text={"At SIRION SRL we are committed not only to providing high-quality products but also to doing so in a sustainable and environmentally responsible manner. We recognize the importance of reducing the environmental impact of our operations and are taking concrete steps to achieve this goal. We have initiated a process of calculating the CO2 emissions generated by our activities and are committed to compensating them through carbon footprint certifications, ensuring an increasingly reduced ecological footprint."} 
                text2={"Furthermore, we are excited to announce that during the year we will install the first phase of a large-scale project dedicated to renewable energy. This project involves the installation of photovoltaic panels for the production of clean and sustainable energy, further reducing our environmental impact and contributing to the transition towards a greener and more sustainable future."}
                text3={"Continue to follow our progress in our mission for a cleaner and more sustainable environment. Together, we can make a difference."}
            />

            <div className="flex flex-col md:flex-row items-center justify-center p-10 bg-customWhite">
                <div className="w-full md:w-1/2 max-w-md md:max-w-800 mx-4 my-2 bg-gray-200 flex items-center justify-center">
                    <Image src={TechImg5} alt='techImage' width={500} height={300}></Image>
                </div>
                <div className="w-full md:w-1/2 max-w-md md:max-w-800 mx-4 my-2 bg-gray-200">
                    <h4 className="mb-4 text-customBlack text-3xl font-medium">CO2 Carbon Footprint Compensation</h4>
                    <p className="mb-4 text-customBlack">
                        Sirion always works with an eye on sustainability and with the help of the company @Upgreene, the first report on the calculation of the CFP Carbon Footprint of the Organization has already been issued. The aim is to calculate the emissive footprint of the organization of Sirion srl and therefore quantify the impact of the actions attributable to the activities of the headquarters on climate change.<br />
                        The total calculated CO2 emissions will be fully offset by UpGreene, allowing Sirion to embark on a path towards climate neutrality.
                    </p>
                    <Link target="_blank" href={'/impronta-new-CO2.pdf'}>
                        <Button text="CO2 FOOTPRINT" />
                    </Link>
                </div>
            </div>
            <div className="flex flex-col md:flex-row items-center justify-center p-10 bg-customWhite">
                <div className="w-full md:w-1/2 max-w-md md:max-w-800 mx-4 my-2 bg-gray-200 md:order-last flex items-center justify-center">
                    <Image src={TechImg1} alt='techImage' width={500} height={300}></Image>
                </div>
                <div className="w-full md:w-1/2 max-w-md md:max-w-800 mx-4 my-2 bg-gray-200 md:order-first">
                    <h4 className="mb-4 text-customBlack text-3xl font-medium">Photovoltaic Panels</h4>
                    <p className="mb-4 text-customBlack">
                        Sirion srl aims to grow also in terms of eco-sustainability. To this end, Sirion is already working on a multi-year project that will, by the end of 2026, allow self-production of energy from photovoltaic panels to cover up to 75% of the demand, thanks also to next-generation electrical systems.
                    </p>
                </div>
            </div>
           
            <EndPage 
                text1={"Research and Innovation"} 
                text2={"Discover how Sirion is committed to continuous research to innovate and meet the needs of customers in the automotive sector."} 
                text3={"Contact Us"} 
                href={"/en/contact"}
            />
            <Footer></Footer>
        </>
    );
}
